# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_squashed_0029_auto_20160724_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=512)),
                ('account_no', models.CharField(max_length=512)),
                ('sort_code', models.CharField(max_length=512)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Company')),
            ],
        ),
    ]
