# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20160112_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 13, 11, 9, 0, 248389, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thought',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('user', 'tag')]),
        ),
    ]
