# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20160113_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=512),
        ),
    ]
