# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-24 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_invoice_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
