# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20160507_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='hourly_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='hours_per_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslip',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Project'),
        ),
    ]
