# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20160507_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslip',
            name='date',
            field=models.DateField(),
        ),
    ]
