# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-01 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20160829_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_due',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_paid',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
