# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20160507_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslip',
            name='minutes',
        ),
        migrations.AddField(
            model_name='timeslip',
            name='hours',
            field=models.FloatField(default=0.0),
        ),
    ]
