# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20160507_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslip',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Invoice'),
        ),
    ]
