# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20160507_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslip',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
