# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20160511_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Account'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.Account'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
