# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_auto_20160511_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal.Account'),
            preserve_default=False,
        ),
    ]
