# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 15:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0017_project_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='account',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
