# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0018_auto_20160515_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Company'),
        ),
    ]
