# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal.Company'),
        ),
    ]
