# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_auto_20160515_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
