# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-14 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_task_tasknote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='predicted_horus',
            new_name='hours_predicted',
        ),
    ]
