# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-19 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_auto_20160619_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sequence_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(default=None),
        ),
    ]
