# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-25 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_auto_20170114_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address1',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='address2',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='post_code',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='vat_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
