# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_auto_20160619_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
