# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_auto_20160619_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInvoiceModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.InvoiceModifier')),
                ('project', models.ManyToManyField(to='journal.Project')),
            ],
        ),
    ]
