# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-25 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_auto_20170325_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('ISSUED', 'ISSUED'), ('PAID', 'PAID')], default='DRAFT', max_length=128),
        ),
    ]
