# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_invoicemodifier_projectinvoicemodifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvoicemodifier',
            name='invoice_modifier',
        ),
        migrations.RemoveField(
            model_name='projectinvoicemodifier',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='invoice_modifier',
            field=models.ManyToManyField(to='journal.InvoiceModifier'),
        ),
        migrations.DeleteModel(
            name='ProjectInvoiceModifier',
        ),
    ]
