# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0030_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(blank=True, null=True, default=None, max_length=256),
        ),
    ]
