# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-04 08:00
from __future__ import unicode_literals

from django.db import migrations

def set_task_invoice(apps, schema_editor):
    Task = apps.get_model('journal', 'Task')
    TaskInvoice = apps.get_model('journal', 'TaskInvoice')

    for task in Task.objects.all():
        invoice = task.invoice

        if invoice:
            task_invoice = TaskInvoice.objects.create(
                task=task,
                invoice=invoice,
                cost=task.cost
            )
            task_invoice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0039_auto_20190704_0759'),
    ]

    operations = [
        migrations.RunPython(set_task_invoice)
    ]
