# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-29 20:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('journal', '0001_initial'), ('journal', '0002_auto_20160112_2210'), ('journal', '0003_auto_20160113_1109'), ('journal', '0004_auto_20160113_1407'), ('journal', '0005_auto_20160114_2120'), ('journal', '0006_contact_project'), ('journal', '0007_auto_20160507_0719'), ('journal', '0008_auto_20160507_0754'), ('journal', '0009_auto_20160507_0756'), ('journal', '0010_auto_20160507_0757'), ('journal', '0011_auto_20160507_1038'), ('journal', '0012_auto_20160507_1050'), ('journal', '0013_auto_20160507_1052'), ('journal', '0014_auto_20160507_1052'), ('journal', '0015_auto_20160511_2019'), ('journal', '0016_auto_20160511_2032'), ('journal', '0017_project_account'), ('journal', '0018_auto_20160515_1527'), ('journal', '0019_contact_company'), ('journal', '0020_auto_20160515_1934'), ('journal', '0021_company_vat_number'), ('journal', '0022_invoiceitem'), ('journal', '0023_timeslip_user'), ('journal', '0024_auto_20160601_2115'), ('journal', '0025_auto_20160619_1323'), ('journal', '0026_auto_20160619_1331'), ('journal', '0027_auto_20160619_1340'), ('journal', '0028_invoicemodifier_projectinvoicemodifier'), ('journal', '0029_auto_20160724_1545')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=512, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 13, 11, 9, 0, 248389, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('user', 'tag')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=512),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Contact')),
                ('hourly_rate', models.IntegerField(default=0)),
                ('hours_per_day', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.CreateModel(
            name='TimeSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Project')),
                ('hours', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_num', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Project')),
            ],
        ),
        migrations.AddField(
            model_name='timeslip',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeslips', to='journal.Invoice'),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='timeslip',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('address1', models.CharField(blank=True, max_length=512, null=True)),
                ('address2', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('post_code', models.CharField(blank=True, max_length=128, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=128, null=True)),
                ('logo_image', models.TextField(blank=True, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='timeslip',
            name='comment',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Account'),
        ),
        migrations.AddField(
            model_name='project',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journal.Company'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('units', models.CharField(max_length=128)),
                ('qty', models.CharField(max_length=128)),
                ('cost_per_unit', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='journal.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='timeslip',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='timeslip',
            unique_together=set([('user', 'project', 'date')]),
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sequence_num',
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sequence_num',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InvoiceModifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('percent', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='invoice_modifier',
            field=models.ManyToManyField(to='journal.InvoiceModifier'),
        ),
    ]
