# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-31 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20160731_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.Billing'),
        ),
    ]
