# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20160731_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
