# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20160824_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='journal.Invoice'),
        ),
    ]
