# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20160825_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='invoice_modifier',
        ),
        migrations.AddField(
            model_name='invoice',
            name='modifier',
            field=models.ManyToManyField(to='journal.InvoiceModifier'),
        ),
    ]
