# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20160901_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal_due',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
