# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20160903_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
