# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0013_auto_20160907_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.IntegerField()),
                ('type', models.CharField(choices=[('TIM', 'TimeSlip'), ('INV', 'Invoice'), ('PRO', 'Project')], max_length=3)),
                ('action', models.CharField(choices=[('CRE', 'Create'), ('UPD', 'Update'), ('DEL', 'Delete')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
