# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-25 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_timeslip_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslip',
            name='created_by',
        ),
    ]
