# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_auto_20170114_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknote',
            name='content',
        ),
        migrations.AddField(
            model_name='tasknote',
            name='conent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
