# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-14 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_auto_20170114_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasknote',
            old_name='conent',
            new_name='content',
        ),
    ]
