# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-25 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
    ]
