# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-14 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0029_remove_contact_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
    ]
