# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0033_auto_20190602_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_default', to='journal.Task'),
        ),
        migrations.AddField(
            model_name='timeslip',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Task'),
        ),
    ]
