# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-22 12:29
from __future__ import unicode_literals

from django.db import migrations


def create_default_tasks(apps, schema_editor):
    Project = apps.get_model('journal', 'Project')
    Task = apps.get_model('journal', 'Task')

    projects = Project.objects.all()

    for project in projects:
        task_name = f'Default Task ({project.name})'
        task = Task.objects.create(
            name=task_name,
            user=project.account.users.first(),
            project=project,
        )
        project.default_task = task
        project.save()


def set_timeslip_defaults(apps, schema_editor):
    TimeSlip = apps.get_model('journal', 'TimeSlip')
    timeslips = TimeSlip.objects.all()

    for timeslip in timeslips:
        timeslip.task = timeslip.project.default_task
        timeslip.save()



class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0034_auto_20190622_1229'),
    ]

    operations = [
        migrations.RunPython(create_default_tasks),
        migrations.RunPython(set_timeslip_defaults),
    ]
