# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0035_auto_20190622_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activity_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
