# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-22 12:57
from __future__ import unicode_literals

from django.db import migrations


def set_task_activity_at(apps, schema_editor):
    Task = apps.get_model('journal', 'Task')
    TimeSlip = apps.get_model('journal', 'TimeSlip')

    tasks = Task.objects.all()

    for task in tasks:
        timeslip = TimeSlip.objects.filter(
            project=task.project
        ).order_by('-created_at').first()
        if timeslip:
            task.activity_at = timeslip.created_at
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0036_task_activity_at'),
    ]

    operations = [
        migrations.RunPython(set_task_activity_at),
    ]
