# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-06-27 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0037_auto_20190622_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='billing_type',
            field=models.CharField(choices=[('TIME', 'Time'), ('FIXED', 'Fixed Cost')], default='TIME', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='timeslip',
            unique_together=set([('user', 'task', 'date')]),
        ),
    ]
