# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-04 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0038_auto_20190627_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Invoice')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='invoices',
            field=models.ManyToManyField(through='journal.TaskInvoice', to='journal.Invoice'),
        ),
    ]
