# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-10 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0041_auto_20190704_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='group_by',
            field=models.CharField(choices=[('tasks', 'Task'), ('timeslips', 'Timeslip')], default='timeslips', max_length=128),
        ),
        migrations.AddField(
            model_name='invoice',
            name='show_hours',
            field=models.BooleanField(default=True),
        ),
    ]
