# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-10-12 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0043_task_billable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='billable',
        ),
        migrations.AddField(
            model_name='timeslip',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
