# Generated by Django 3.0.4 on 2021-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0049_auto_20200323_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='iban',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='swift',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
