# Generated by Django 3.0.4 on 2021-07-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0050_auto_20210621_1509"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journal.Company",
            ),
        ),
    ]
