# Generated by Django 3.0.4 on 2021-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0052_auto_20210728_1528"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="weekly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
