# Generated by Django 3.0.4 on 2021-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0053_project_weekly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
    ]
