# Generated by Django 3.0.4 on 2021-11-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0054_auto_20210902_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sso_domain',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
