# Generated by Django 3.0.4 on 2022-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0055_account_sso_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_unit',
            field=models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week')], default='HOUR', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='billing_unit',
            field=models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week')], default='HOUR', max_length=128, null=True),
        ),
    ]
