version: '2'
services:
  soitgoes:
    stdin_open: true
    tty: true
    env_file:
      - env_variables
    build:
      context: .
      dockerfile: Dockerfile
    command: python api/manage.py runserver 0.0.0.0:8001
    ports:
     - "8001:8001"
    volumes:
      - ./api:/app/api
      - ./client/dist:/app/journal/static/journal/dist
