FROM node:10.15.1

RUN mkdir /app

ADD client/package.json /app/package.json
WORKDIR /app
RUN npm install

ADD client/webpack.config.js /app/webpack.config.js
ADD client/src /app/src
ADD client/.babelrc /app/.babelrc
ADD client/.eslintrc /app/.eslintrc
