version: '2'
services:
  soitgoes:
    stdin_open: true
    tty: true
    environment:
     - DEV=true
    build:
      context: .
      dockerfile: Dockerfile
    command: python api/manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    volumes:
      - ./api:/app/api
      - ./client/dist:/app/journal/static/journal/dist
