FROM node:7.9.0

RUN mkdir /app

ADD journal/static/journal/package.json /app/package.json
WORKDIR /app
RUN yarn

ADD journal/static/journal/webpack.config.js /app/webpack.config.js
ADD journal/static/journal/src /app/src
ADD journal/static/journal/.babelrc /app/.babelrc
ADD journal/static/journal/.eslintrc /app/.eslintrc
