version: '2'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile-nodejs
    ports:
     - "8080:8080"
    volumes:
      - ./client/src:/app/src
      - ./client/dist:/app/dist
      - ./client/index.html:/app/index.html
      - ./client/package.json:/app/package.json
      - ./client/webpack.config.js:/app/webpack.config.js
      - ./client/.babelrc:/app/.babelrc
    command: npm run start:dev

  soitgoes:
    stdin_open: true
    tty: true
    environment:
     - DEV=true
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    depends_on:
     - nodejs
    volumes:
      - ./journal:/app/journal
      - ./adminsheets:/app/adminsheets
      - ./soitgoes:/app/soitgoes
      - ./libs:/app/libs
      - ./assets:/app/assets
      - ./client/dist:/app/journal/static/journal/dist
      - ./db.sqlite3:/app/db.sqlite3
