/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimeRouteImport } from './routes/time'
import { Route as InvoicesRouteRouteImport } from './routes/invoices/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as ContactsContactIdRouteImport } from './routes/contacts/$contactId'
import { Route as InvoicesProjectIdIndexRouteImport } from './routes/invoices/$projectId/index'
import { Route as InvoicesProjectIdInvoiceIdRouteImport } from './routes/invoices/$projectId/$invoiceId'

const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRouteRoute = InvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRouteRoute,
} as any)
const ContactsContactIdRoute = ContactsContactIdRouteImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesProjectIdIndexRoute = InvoicesProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => InvoicesRouteRoute,
} as any)
const InvoicesProjectIdInvoiceIdRoute =
  InvoicesProjectIdInvoiceIdRouteImport.update({
    id: '/$projectId/$invoiceId',
    path: '/$projectId/$invoiceId',
    getParentRoute: () => InvoicesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRouteRouteWithChildren
  '/time': typeof TimeRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/contacts': typeof ContactsIndexRoute
  '/invoices/$projectId/$invoiceId': typeof InvoicesProjectIdInvoiceIdRoute
  '/invoices/$projectId': typeof InvoicesProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRouteRouteWithChildren
  '/time': typeof TimeRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/contacts': typeof ContactsIndexRoute
  '/invoices/$projectId/$invoiceId': typeof InvoicesProjectIdInvoiceIdRoute
  '/invoices/$projectId': typeof InvoicesProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRouteRouteWithChildren
  '/time': typeof TimeRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/contacts/': typeof ContactsIndexRoute
  '/invoices/$projectId/$invoiceId': typeof InvoicesProjectIdInvoiceIdRoute
  '/invoices/$projectId/': typeof InvoicesProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoices'
    | '/time'
    | '/contacts/$contactId'
    | '/invoices/new'
    | '/contacts'
    | '/invoices/$projectId/$invoiceId'
    | '/invoices/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invoices'
    | '/time'
    | '/contacts/$contactId'
    | '/invoices/new'
    | '/contacts'
    | '/invoices/$projectId/$invoiceId'
    | '/invoices/$projectId'
  id:
    | '__root__'
    | '/'
    | '/invoices'
    | '/time'
    | '/contacts/$contactId'
    | '/invoices/new'
    | '/contacts/'
    | '/invoices/$projectId/$invoiceId'
    | '/invoices/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvoicesRouteRoute: typeof InvoicesRouteRouteWithChildren
  TimeRoute: typeof TimeRoute
  ContactsContactIdRoute: typeof ContactsContactIdRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRouteRoute
    }
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$projectId/': {
      id: '/invoices/$projectId/'
      path: '/$projectId'
      fullPath: '/invoices/$projectId'
      preLoaderRoute: typeof InvoicesProjectIdIndexRouteImport
      parentRoute: typeof InvoicesRouteRoute
    }
    '/invoices/$projectId/$invoiceId': {
      id: '/invoices/$projectId/$invoiceId'
      path: '/$projectId/$invoiceId'
      fullPath: '/invoices/$projectId/$invoiceId'
      preLoaderRoute: typeof InvoicesProjectIdInvoiceIdRouteImport
      parentRoute: typeof InvoicesRouteRoute
    }
  }
}

interface InvoicesRouteRouteChildren {
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesProjectIdInvoiceIdRoute: typeof InvoicesProjectIdInvoiceIdRoute
  InvoicesProjectIdIndexRoute: typeof InvoicesProjectIdIndexRoute
}

const InvoicesRouteRouteChildren: InvoicesRouteRouteChildren = {
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesProjectIdInvoiceIdRoute: InvoicesProjectIdInvoiceIdRoute,
  InvoicesProjectIdIndexRoute: InvoicesProjectIdIndexRoute,
}

const InvoicesRouteRouteWithChildren = InvoicesRouteRoute._addFileChildren(
  InvoicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvoicesRouteRoute: InvoicesRouteRouteWithChildren,
  TimeRoute: TimeRoute,
  ContactsContactIdRoute: ContactsContactIdRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
