// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type OneTimeToken = {
    key: string;
};

export type User = {
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    last_login?: string | null;
};

export type Note = {
    readonly id?: number;
    content: string;
    contact: number;
    readonly created_at?: string;
};

export type Project = {
    readonly id?: number;
    name: string;
    contact: number;
    readonly created_at?: string;
    readonly uninvoiced_hours?: number;
    readonly total_paid?: number;
    hourly_rate?: number;
    weekly_rate?: number | null;
    archived?: boolean;
    currency?: string;
    default_task?: number | null;
    readonly next_sequence_num?: string;
    billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
};

export type ProjectSummary = {
    unbilled: Array<{
        readonly project?: {
            readonly id?: number;
            name: string;
            contact: number;
            readonly created_at?: string;
            readonly uninvoiced_hours?: number;
            readonly total_paid?: number;
            hourly_rate?: number;
            weekly_rate?: number | null;
            archived?: boolean;
            currency?: string;
            default_task?: number | null;
            readonly next_sequence_num?: string;
            billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
        };
        readonly hours?: number;
        readonly total?: number;
        readonly next_sequence_num?: number;
        readonly previous_invoice?: {
            readonly id?: number;
            sequence_num?: number;
            project: number;
            readonly created_at?: string;
            readonly issued_at?: string | null;
            paid_at?: string | null;
            due_date?: string | null;
            total_paid?: number | null;
            total_due?: number | null;
            subtotal_due?: number | null;
            status?: 'DRAFT' | 'ISSUED' | 'PAID';
            reference?: string | null;
            group_by?: 'tasks' | 'timeslips';
            show_hours?: boolean;
            timeslips: Array<number>;
            tasks: Array<number>;
            modifier?: Array<number>;
            readonly pdf_name?: string;
            readonly name?: string;
            exchange_rate?: number;
            currency?: string;
            billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
        };
    }>;
    invoices: Array<{
        readonly project?: {
            readonly id?: number;
            name: string;
            contact: number;
            readonly created_at?: string;
            readonly uninvoiced_hours?: number;
            readonly total_paid?: number;
            hourly_rate?: number;
            weekly_rate?: number | null;
            archived?: boolean;
            currency?: string;
            default_task?: number | null;
            readonly next_sequence_num?: string;
            billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
        };
        readonly total_invoiced?: number;
        readonly subtotal_invoiced?: number;
        readonly total_paid?: number;
        readonly total_unpaid?: number;
        readonly invoice_count?: number;
        readonly six_month_subtotal_invoiced?: number;
        readonly six_month_total_invoiced?: number;
        readonly six_month_total_paid?: number;
        readonly six_month_total_unpaid?: number;
        readonly six_month_invoice_count?: number;
    }>;
};

export type Invoice = {
    readonly id?: number;
    sequence_num?: number;
    project: number;
    readonly created_at?: string;
    readonly issued_at?: string | null;
    paid_at?: string | null;
    due_date?: string | null;
    total_paid?: number | null;
    total_due?: number | null;
    subtotal_due?: number | null;
    status?: 'DRAFT' | 'ISSUED' | 'PAID';
    reference?: string | null;
    group_by?: 'tasks' | 'timeslips';
    show_hours?: boolean;
    timeslips: Array<number>;
    tasks: Array<number>;
    modifier?: Array<number>;
    readonly pdf_name?: string;
    readonly name?: string;
    exchange_rate?: number;
    currency?: string;
    billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
};

export type TimeSlip = {
    readonly id?: number;
    user: number;
    hours?: number;
    hourly_rate?: number;
    project: number;
    task: number | null;
    invoice?: number | null;
    readonly cost?: number;
    date: string;
};

export type InvoiceModifier = {
    readonly id?: number;
    name: string;
    percent?: number;
    readonly created_at?: string;
};

export type Account = {
    readonly id?: number;
    company: {
        readonly id?: number;
        name: string;
        billing?: number | null;
        logo_image?: string | null;
        contacts: Array<number>;
    };
};

export type Task = {
    readonly id?: number;
    project: number;
    name: string;
    cost?: number;
    readonly created_at?: string;
    readonly activity_at?: string | null;
    completed_at?: string | null;
    due_date?: string | null;
    hours_spent?: number;
    hours_predicted?: number;
    billing_type?: 'TIME' | 'FIXED';
    state?: 'OPEN' | 'PROGRESS' | 'DONE';
    readonly invoices?: Array<string>;
    readonly notes?: Array<{
        content?: string | null;
        content_type?: 'TEXT';
    }>;
};

export type TaskSummary = {
    invoices: Array<{
        readonly id?: number;
        sequence_num?: number;
        project: number;
        readonly created_at?: string;
        readonly issued_at?: string | null;
        paid_at?: string | null;
        due_date?: string | null;
        total_paid?: number | null;
        total_due?: number | null;
        subtotal_due?: number | null;
        status?: 'DRAFT' | 'ISSUED' | 'PAID';
        reference?: string | null;
        group_by?: 'tasks' | 'timeslips';
        show_hours?: boolean;
        timeslips: Array<number>;
        tasks: Array<number>;
        modifier?: Array<number>;
        readonly pdf_name?: string;
        readonly name?: string;
        exchange_rate?: number;
        currency?: string;
        billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
    }>;
    timeslips: Array<{
        readonly id?: number;
        user: number;
        hours?: number;
        hourly_rate?: number;
        project: number;
        task: number | null;
        invoice?: number | null;
        readonly cost?: number;
        date: string;
    }>;
};

export type Contact = {
    readonly id?: number;
    name: string;
    email: string;
    readonly created_at?: string;
    readonly account?: string;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    post_code?: string | null;
    company?: number | null;
};

export type Company = {
    readonly id?: number;
    name: string;
    billing?: number | null;
    logo_image?: string | null;
    contacts: Array<number>;
};

export type Version = {
    readonly git_branch?: string;
    readonly git_rev?: string;
};

export type ExchangeRate = {
    readonly rates?: {
        [key: string]: unknown;
    };
};

export type Sso = {
    code: string;
    readonly token?: string;
};

export type Login = {
    email: string;
    password: string;
    readonly token?: string;
};

export type UserWritable = {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    last_login?: string | null;
};

export type NoteWritable = {
    content: string;
    contact: number;
};

export type ProjectWritable = {
    name: string;
    contact: number;
    hourly_rate?: number;
    weekly_rate?: number | null;
    archived?: boolean;
    currency?: string;
    default_task?: number | null;
    billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
};

export type ProjectSummaryWritable = {
    unbilled: Array<unknown>;
    invoices: Array<unknown>;
};

export type InvoiceWritable = {
    sequence_num?: number;
    project: number;
    paid_at?: string | null;
    due_date?: string | null;
    total_paid?: number | null;
    total_due?: number | null;
    subtotal_due?: number | null;
    status?: 'DRAFT' | 'ISSUED' | 'PAID';
    reference?: string | null;
    group_by?: 'tasks' | 'timeslips';
    show_hours?: boolean;
    timeslips: Array<number>;
    tasks: Array<number>;
    modifier?: Array<number>;
    exchange_rate?: number;
    currency?: string;
    billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
};

export type TimeSlipWritable = {
    user: number;
    hours?: number;
    hourly_rate?: number;
    project: number;
    task: number | null;
    invoice?: number | null;
    date: string;
};

export type InvoiceModifierWritable = {
    name: string;
    percent?: number;
};

export type AccountWritable = {
    company: {
        name: string;
        billing?: number | null;
        logo_image?: string | null;
        contacts: Array<number>;
    };
};

export type TaskWritable = {
    project: number;
    name: string;
    cost?: number;
    completed_at?: string | null;
    due_date?: string | null;
    hours_spent?: number;
    hours_predicted?: number;
    billing_type?: 'TIME' | 'FIXED';
    state?: 'OPEN' | 'PROGRESS' | 'DONE';
};

export type TaskSummaryWritable = {
    invoices: Array<{
        sequence_num?: number;
        project: number;
        paid_at?: string | null;
        due_date?: string | null;
        total_paid?: number | null;
        total_due?: number | null;
        subtotal_due?: number | null;
        status?: 'DRAFT' | 'ISSUED' | 'PAID';
        reference?: string | null;
        group_by?: 'tasks' | 'timeslips';
        show_hours?: boolean;
        timeslips: Array<number>;
        tasks: Array<number>;
        modifier?: Array<number>;
        exchange_rate?: number;
        currency?: string;
        billing_unit?: 'HOUR' | 'DAY' | 'WEEK';
    }>;
    timeslips: Array<{
        user: number;
        hours?: number;
        hourly_rate?: number;
        project: number;
        task: number | null;
        invoice?: number | null;
        date: string;
    }>;
};

export type ContactWritable = {
    name: string;
    email: string;
    address1?: string | null;
    address2?: string | null;
    city?: string | null;
    post_code?: string | null;
    company?: number | null;
};

export type CompanyWritable = {
    name: string;
    billing?: number | null;
    logo_image?: string | null;
    contacts: Array<number>;
};

export type RetrieveOneTimeTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/token/';
};

export type RetrieveOneTimeTokenResponses = {
    200: OneTimeToken;
};

export type RetrieveOneTimeTokenResponse = RetrieveOneTimeTokenResponses[keyof RetrieveOneTimeTokenResponses];

export type RetrieveUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type RetrieveUserResponses = {
    200: User;
};

export type RetrieveUserResponse = RetrieveUserResponses[keyof RetrieveUserResponses];

export type ListNotesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * contact
         */
        contact?: string;
    };
    url: '/api/crm/note/';
};

export type ListNotesResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<Note>;
    };
};

export type ListNotesResponse = ListNotesResponses[keyof ListNotesResponses];

export type CreateNoteData = {
    body?: NoteWritable;
    path?: never;
    query?: never;
    url: '/api/crm/note/';
};

export type CreateNoteResponses = {
    201: Note;
};

export type CreateNoteResponse = CreateNoteResponses[keyof CreateNoteResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/projects/';
};

export type ListProjectsResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<Project>;
    };
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body?: ProjectWritable;
    path?: never;
    query?: never;
    url: '/api/projects/';
};

export type CreateProjectResponses = {
    201: Project;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type ListProjectSummariesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/projects/summary/';
};

export type ListProjectSummariesResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<ProjectSummary>;
    };
};

export type ListProjectSummariesResponse = ListProjectSummariesResponses[keyof ListProjectSummariesResponses];

export type DestroyProjectData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this project.
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type DestroyProjectResponses = {
    204: void;
};

export type DestroyProjectResponse = DestroyProjectResponses[keyof DestroyProjectResponses];

export type RetrieveProjectData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this project.
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type RetrieveProjectResponses = {
    200: Project;
};

export type RetrieveProjectResponse = RetrieveProjectResponses[keyof RetrieveProjectResponses];

export type PartialUpdateProjectData = {
    body?: ProjectWritable;
    path: {
        /**
         * A unique integer value identifying this project.
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type PartialUpdateProjectResponses = {
    200: Project;
};

export type PartialUpdateProjectResponse = PartialUpdateProjectResponses[keyof PartialUpdateProjectResponses];

export type UpdateProjectData = {
    body?: ProjectWritable;
    path: {
        /**
         * A unique integer value identifying this project.
         */
        id: string;
    };
    query?: never;
    url: '/api/projects/{id}';
};

export type UpdateProjectResponses = {
    200: Project;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type ListInvoicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/invoices/';
};

export type ListInvoicesResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<Invoice>;
    };
};

export type ListInvoicesResponse = ListInvoicesResponses[keyof ListInvoicesResponses];

export type CreateInvoiceData = {
    body?: InvoiceWritable;
    path?: never;
    query?: never;
    url: '/api/invoices/';
};

export type CreateInvoiceResponses = {
    201: Invoice;
};

export type CreateInvoiceResponse = CreateInvoiceResponses[keyof CreateInvoiceResponses];

export type ListTimeSlipsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * invoice
         */
        invoice?: string;
        /**
         * project
         */
        project?: string;
        /**
         * start
         */
        start?: string;
        /**
         * end
         */
        end?: string;
        /**
         * no_invoice
         */
        no_invoice?: string;
    };
    url: '/api/timeslips/';
};

export type ListTimeSlipsResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<TimeSlip>;
    };
};

export type ListTimeSlipsResponse = ListTimeSlipsResponses[keyof ListTimeSlipsResponses];

export type CreateTimeSlipData = {
    body?: TimeSlipWritable;
    path?: never;
    query?: never;
    url: '/api/timeslips/';
};

export type CreateTimeSlipResponses = {
    201: TimeSlip;
};

export type CreateTimeSlipResponse = CreateTimeSlipResponses[keyof CreateTimeSlipResponses];

export type DestroyTimeSlipData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this time slip.
         */
        id: string;
    };
    query?: never;
    url: '/api/timeslips/{id}';
};

export type DestroyTimeSlipResponses = {
    204: void;
};

export type DestroyTimeSlipResponse = DestroyTimeSlipResponses[keyof DestroyTimeSlipResponses];

export type RetrieveTimeSlipData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this time slip.
         */
        id: string;
    };
    query?: never;
    url: '/api/timeslips/{id}';
};

export type RetrieveTimeSlipResponses = {
    200: TimeSlip;
};

export type RetrieveTimeSlipResponse = RetrieveTimeSlipResponses[keyof RetrieveTimeSlipResponses];

export type PartialUpdateTimeSlipData = {
    body?: TimeSlipWritable;
    path: {
        /**
         * A unique integer value identifying this time slip.
         */
        id: string;
    };
    query?: never;
    url: '/api/timeslips/{id}';
};

export type PartialUpdateTimeSlipResponses = {
    200: TimeSlip;
};

export type PartialUpdateTimeSlipResponse = PartialUpdateTimeSlipResponses[keyof PartialUpdateTimeSlipResponses];

export type UpdateTimeSlipData = {
    body?: TimeSlipWritable;
    path: {
        /**
         * A unique integer value identifying this time slip.
         */
        id: string;
    };
    query?: never;
    url: '/api/timeslips/{id}';
};

export type UpdateTimeSlipResponses = {
    200: TimeSlip;
};

export type UpdateTimeSlipResponse = UpdateTimeSlipResponses[keyof UpdateTimeSlipResponses];

export type DestroyInvoiceData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this invoice.
         */
        id: string;
    };
    query?: never;
    url: '/api/invoices/{id}';
};

export type DestroyInvoiceResponses = {
    204: void;
};

export type DestroyInvoiceResponse = DestroyInvoiceResponses[keyof DestroyInvoiceResponses];

export type RetrieveInvoiceData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this invoice.
         */
        id: string;
    };
    query?: never;
    url: '/api/invoices/{id}';
};

export type RetrieveInvoiceResponses = {
    200: Invoice;
};

export type RetrieveInvoiceResponse = RetrieveInvoiceResponses[keyof RetrieveInvoiceResponses];

export type PartialUpdateInvoiceData = {
    body?: InvoiceWritable;
    path: {
        /**
         * A unique integer value identifying this invoice.
         */
        id: string;
    };
    query?: never;
    url: '/api/invoices/{id}';
};

export type PartialUpdateInvoiceResponses = {
    200: Invoice;
};

export type PartialUpdateInvoiceResponse = PartialUpdateInvoiceResponses[keyof PartialUpdateInvoiceResponses];

export type UpdateInvoiceData = {
    body?: InvoiceWritable;
    path: {
        /**
         * A unique integer value identifying this invoice.
         */
        id: string;
    };
    query?: never;
    url: '/api/invoices/{id}';
};

export type UpdateInvoiceResponses = {
    200: Invoice;
};

export type UpdateInvoiceResponse = UpdateInvoiceResponses[keyof UpdateInvoiceResponses];

export type ListInvoicePdfsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/invoices/{id}/pdf';
};

export type ListInvoicePdfsResponses = {
    200: Array<unknown>;
};

export type ListInvoicePdfsResponse = ListInvoicePdfsResponses[keyof ListInvoicePdfsResponses];

export type ListBulkInvoicePdfsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/invoices/zip';
};

export type ListBulkInvoicePdfsResponses = {
    200: Array<unknown>;
};

export type ListBulkInvoicePdfsResponse = ListBulkInvoicePdfsResponses[keyof ListBulkInvoicePdfsResponses];

export type DestroyInvoiceModifierData = {
    body?: never;
    path: {
        id: string;
        modifier: string;
    };
    query?: never;
    url: '/api/invoices/{id}/modifiers/{modifier}';
};

export type DestroyInvoiceModifierResponses = {
    204: void;
};

export type DestroyInvoiceModifierResponse = DestroyInvoiceModifierResponses[keyof DestroyInvoiceModifierResponses];

export type RetrieveInvoiceModifierData = {
    body?: never;
    path: {
        id: string;
        modifier: string;
    };
    query?: never;
    url: '/api/invoices/{id}/modifiers/{modifier}';
};

export type RetrieveInvoiceModifierResponses = {
    200: InvoiceModifier;
};

export type RetrieveInvoiceModifierResponse = RetrieveInvoiceModifierResponses[keyof RetrieveInvoiceModifierResponses];

export type PartialUpdateInvoiceModifierData = {
    body?: InvoiceModifierWritable;
    path: {
        id: string;
        modifier: string;
    };
    query?: never;
    url: '/api/invoices/{id}/modifiers/{modifier}';
};

export type PartialUpdateInvoiceModifierResponses = {
    200: InvoiceModifier;
};

export type PartialUpdateInvoiceModifierResponse = PartialUpdateInvoiceModifierResponses[keyof PartialUpdateInvoiceModifierResponses];

export type UpdateInvoiceModifierData = {
    body?: InvoiceModifierWritable;
    path: {
        id: string;
        modifier: string;
    };
    query?: never;
    url: '/api/invoices/{id}/modifiers/{modifier}';
};

export type UpdateInvoiceModifierResponses = {
    200: InvoiceModifier;
};

export type UpdateInvoiceModifierResponse = UpdateInvoiceModifierResponses[keyof UpdateInvoiceModifierResponses];

export type ListAccountsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/accounts/';
};

export type ListAccountsResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<Account>;
    };
};

export type ListAccountsResponse = ListAccountsResponses[keyof ListAccountsResponses];

export type ListTasksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * invoices
         */
        invoices?: string;
        /**
         * project
         */
        project?: string;
        /**
         * no_invoice
         */
        no_invoice?: string;
        /**
         * billing_type
         */
        billing_type?: 'TIME' | 'FIXED';
        /**
         * state
         */
        state?: 'OPEN' | 'PROGRESS' | 'DONE';
    };
    url: '/api/tasks/';
};

export type ListTasksResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<Task>;
    };
};

export type ListTasksResponse = ListTasksResponses[keyof ListTasksResponses];

export type CreateTaskData = {
    body?: TaskWritable;
    path?: never;
    query?: never;
    url: '/api/tasks/';
};

export type CreateTaskResponses = {
    201: Task;
};

export type CreateTaskResponse = CreateTaskResponses[keyof CreateTaskResponses];

export type DestroyTaskData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type DestroyTaskResponses = {
    204: void;
};

export type DestroyTaskResponse = DestroyTaskResponses[keyof DestroyTaskResponses];

export type RetrieveTaskData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type RetrieveTaskResponses = {
    200: Task;
};

export type RetrieveTaskResponse = RetrieveTaskResponses[keyof RetrieveTaskResponses];

export type PartialUpdateTaskData = {
    body?: TaskWritable;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type PartialUpdateTaskResponses = {
    200: Task;
};

export type PartialUpdateTaskResponse = PartialUpdateTaskResponses[keyof PartialUpdateTaskResponses];

export type UpdateTaskData = {
    body?: TaskWritable;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type UpdateTaskResponses = {
    200: Task;
};

export type UpdateTaskResponse = UpdateTaskResponses[keyof UpdateTaskResponses];

export type RetrieveTaskSummaryData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this task.
         */
        id: string;
    };
    query?: never;
    url: '/api/tasks/{id}/summary';
};

export type RetrieveTaskSummaryResponses = {
    200: TaskSummary;
};

export type RetrieveTaskSummaryResponse = RetrieveTaskSummaryResponses[keyof RetrieveTaskSummaryResponses];

export type ListContactsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
        /**
         * search
         */
        search?: string;
    };
    url: '/api/contacts/';
};

export type ListContactsResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<Contact>;
    };
};

export type ListContactsResponse = ListContactsResponses[keyof ListContactsResponses];

export type CreateContactData = {
    body?: ContactWritable;
    path?: never;
    query?: never;
    url: '/api/contacts/';
};

export type CreateContactResponses = {
    201: Contact;
};

export type CreateContactResponse = CreateContactResponses[keyof CreateContactResponses];

export type DestroyContactData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this contact.
         */
        id: string;
    };
    query?: never;
    url: '/api/contacts/{id}';
};

export type DestroyContactResponses = {
    204: void;
};

export type DestroyContactResponse = DestroyContactResponses[keyof DestroyContactResponses];

export type RetrieveContactData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this contact.
         */
        id: string;
    };
    query?: never;
    url: '/api/contacts/{id}';
};

export type RetrieveContactResponses = {
    200: Contact;
};

export type RetrieveContactResponse = RetrieveContactResponses[keyof RetrieveContactResponses];

export type PartialUpdateContactData = {
    body?: ContactWritable;
    path: {
        /**
         * A unique integer value identifying this contact.
         */
        id: string;
    };
    query?: never;
    url: '/api/contacts/{id}';
};

export type PartialUpdateContactResponses = {
    200: Contact;
};

export type PartialUpdateContactResponse = PartialUpdateContactResponses[keyof PartialUpdateContactResponses];

export type UpdateContactData = {
    body?: ContactWritable;
    path: {
        /**
         * A unique integer value identifying this contact.
         */
        id: string;
    };
    query?: never;
    url: '/api/contacts/{id}';
};

export type UpdateContactResponses = {
    200: Contact;
};

export type UpdateContactResponse = UpdateContactResponses[keyof UpdateContactResponses];

export type ListInvoiceModifiersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/modifiers/';
};

export type ListInvoiceModifiersResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<InvoiceModifier>;
    };
};

export type ListInvoiceModifiersResponse = ListInvoiceModifiersResponses[keyof ListInvoiceModifiersResponses];

export type ListCompaniesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of results to return per page.
         */
        limit?: number;
        /**
         * The initial index from which to return the results.
         */
        offset?: number;
    };
    url: '/api/companies/';
};

export type ListCompaniesResponses = {
    200: {
        count: number;
        next?: string | null;
        previous?: string | null;
        results: Array<Company>;
    };
};

export type ListCompaniesResponse = ListCompaniesResponses[keyof ListCompaniesResponses];

export type CreateCompanyData = {
    body?: CompanyWritable;
    path?: never;
    query?: never;
    url: '/api/companies/';
};

export type CreateCompanyResponses = {
    201: Company;
};

export type CreateCompanyResponse = CreateCompanyResponses[keyof CreateCompanyResponses];

export type DestroyCompanyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this company.
         */
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type DestroyCompanyResponses = {
    204: void;
};

export type DestroyCompanyResponse = DestroyCompanyResponses[keyof DestroyCompanyResponses];

export type RetrieveCompanyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this company.
         */
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type RetrieveCompanyResponses = {
    200: Company;
};

export type RetrieveCompanyResponse = RetrieveCompanyResponses[keyof RetrieveCompanyResponses];

export type PartialUpdateCompanyData = {
    body?: CompanyWritable;
    path: {
        /**
         * A unique integer value identifying this company.
         */
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type PartialUpdateCompanyResponses = {
    200: Company;
};

export type PartialUpdateCompanyResponse = PartialUpdateCompanyResponses[keyof PartialUpdateCompanyResponses];

export type UpdateCompanyData = {
    body?: CompanyWritable;
    path: {
        /**
         * A unique integer value identifying this company.
         */
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type UpdateCompanyResponses = {
    200: Company;
};

export type UpdateCompanyResponse = UpdateCompanyResponses[keyof UpdateCompanyResponses];

export type RetrieveVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/version/';
};

export type RetrieveVersionResponses = {
    200: Version;
};

export type RetrieveVersionResponse = RetrieveVersionResponses[keyof RetrieveVersionResponses];

export type RetrieveExchangeRateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/currency/rates/';
};

export type RetrieveExchangeRateResponses = {
    200: ExchangeRate;
};

export type RetrieveExchangeRateResponse = RetrieveExchangeRateResponses[keyof RetrieveExchangeRateResponses];

export type CreateSsoData = {
    body?: Sso;
    path?: never;
    query?: never;
    url: '/api/users/sso/';
};

export type CreateSsoResponses = {
    201: Sso;
};

export type CreateSsoResponse = CreateSsoResponses[keyof CreateSsoResponses];

export type CreateLoginData = {
    body?: Login;
    path?: never;
    query?: never;
    url: '/api/users/login/';
};

export type CreateLoginResponses = {
    201: Login;
};

export type CreateLoginResponse = CreateLoginResponses[keyof CreateLoginResponses];
