/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AccountCompany,
    AccountCompanyFromJSON,
    AccountCompanyFromJSONTyped,
    AccountCompanyToJSON,
    AccountUsers,
    AccountUsersFromJSON,
    AccountUsersFromJSONTyped,
    AccountUsersToJSON,
} from './';

/**
 * 
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    readonly id?: number;
    /**
     * 
     * @type {AccountCompany}
     * @memberof Account
     */
    company: AccountCompany;
    /**
     * 
     * @type {Array<AccountUsers>}
     * @memberof Account
     */
    readonly users?: Array<AccountUsers>;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'company': AccountCompanyFromJSON(json['company']),
        'users': !exists(json, 'users') ? undefined : ((json['users'] as Array<any>).map(AccountUsersFromJSON)),
    };
}

export function AccountToJSON(value?: Account | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'company': AccountCompanyToJSON(value.company),
    };
}


