/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Contact
 */
export interface Contact {
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    email: string;
    /**
     * 
     * @type {Date}
     * @memberof Contact
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    address1?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    address2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Contact
     */
    postCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Contact
     */
    company?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof Contact
     */
    projects: Array<number>;
}

export function ContactFromJSON(json: any): Contact {
    return ContactFromJSONTyped(json, false);
}

export function ContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contact {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'email': json['email'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'address1': !exists(json, 'address1') ? undefined : json['address1'],
        'address2': !exists(json, 'address2') ? undefined : json['address2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'postCode': !exists(json, 'post_code') ? undefined : json['post_code'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'projects': json['projects'],
    };
}

export function ContactToJSON(value?: Contact | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'address1': value.address1,
        'address2': value.address2,
        'city': value.city,
        'post_code': value.postCode,
        'company': value.company,
        'projects': value.projects,
    };
}


