/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangeRate
 */
export interface ExchangeRate {
    /**
     * 
     * @type {object}
     * @memberof ExchangeRate
     */
    readonly rates?: object;
}

/**
 * Check if a given object implements the ExchangeRate interface.
 */
export function instanceOfExchangeRate(value: object): value is ExchangeRate {
    return true;
}

export function ExchangeRateFromJSON(json: any): ExchangeRate {
    return ExchangeRateFromJSONTyped(json, false);
}

export function ExchangeRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangeRate {
    if (json == null) {
        return json;
    }
    return {
        
        'rates': json['rates'] == null ? undefined : json['rates'],
    };
}

export function ExchangeRateToJSON(json: any): ExchangeRate {
    return ExchangeRateToJSONTyped(json, false);
}

export function ExchangeRateToJSONTyped(value?: Omit<ExchangeRate, 'rates'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

