/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceModifier
 */
export interface InvoiceModifier {
    /**
     * 
     * @type {number}
     * @memberof InvoiceModifier
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof InvoiceModifier
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof InvoiceModifier
     */
    percent?: number;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceModifier
     */
    readonly createdAt?: Date;
}

/**
 * Check if a given object implements the InvoiceModifier interface.
 */
export function instanceOfInvoiceModifier(value: object): value is InvoiceModifier {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function InvoiceModifierFromJSON(json: any): InvoiceModifier {
    return InvoiceModifierFromJSONTyped(json, false);
}

export function InvoiceModifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceModifier {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'percent': json['percent'] == null ? undefined : json['percent'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function InvoiceModifierToJSON(json: any): InvoiceModifier {
    return InvoiceModifierToJSONTyped(json, false);
}

export function InvoiceModifierToJSONTyped(value?: Omit<InvoiceModifier, 'id'|'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'percent': value['percent'],
    };
}

