/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceModifier
 */
export interface InvoiceModifier {
    /**
     * 
     * @type {number}
     * @memberof InvoiceModifier
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof InvoiceModifier
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof InvoiceModifier
     */
    percent?: number;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceModifier
     */
    readonly createdAt?: Date;
}

export function InvoiceModifierFromJSON(json: any): InvoiceModifier {
    return InvoiceModifierFromJSONTyped(json, false);
}

export function InvoiceModifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceModifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'percent': !exists(json, 'percent') ? undefined : json['percent'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function InvoiceModifierToJSON(value?: InvoiceModifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'percent': value.percent,
    };
}


