/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Contact } from './Contact';
import {
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
    ContactToJSONTyped,
} from './Contact';

/**
 * 
 * @export
 * @interface ListContacts200Response
 */
export interface ListContacts200Response {
    /**
     * 
     * @type {number}
     * @memberof ListContacts200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListContacts200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListContacts200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Contact>}
     * @memberof ListContacts200Response
     */
    results: Array<Contact>;
}

/**
 * Check if a given object implements the ListContacts200Response interface.
 */
export function instanceOfListContacts200Response(value: object): value is ListContacts200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ListContacts200ResponseFromJSON(json: any): ListContacts200Response {
    return ListContacts200ResponseFromJSONTyped(json, false);
}

export function ListContacts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListContacts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ContactFromJSON)),
    };
}

export function ListContacts200ResponseToJSON(json: any): ListContacts200Response {
    return ListContacts200ResponseToJSONTyped(json, false);
}

export function ListContacts200ResponseToJSONTyped(value?: ListContacts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ContactToJSON)),
    };
}

