/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceModifier } from './InvoiceModifier';
import {
    InvoiceModifierFromJSON,
    InvoiceModifierFromJSONTyped,
    InvoiceModifierToJSON,
    InvoiceModifierToJSONTyped,
} from './InvoiceModifier';

/**
 * 
 * @export
 * @interface ListInvoiceModifiers200Response
 */
export interface ListInvoiceModifiers200Response {
    /**
     * 
     * @type {number}
     * @memberof ListInvoiceModifiers200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListInvoiceModifiers200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListInvoiceModifiers200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<InvoiceModifier>}
     * @memberof ListInvoiceModifiers200Response
     */
    results: Array<InvoiceModifier>;
}

/**
 * Check if a given object implements the ListInvoiceModifiers200Response interface.
 */
export function instanceOfListInvoiceModifiers200Response(value: object): value is ListInvoiceModifiers200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ListInvoiceModifiers200ResponseFromJSON(json: any): ListInvoiceModifiers200Response {
    return ListInvoiceModifiers200ResponseFromJSONTyped(json, false);
}

export function ListInvoiceModifiers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvoiceModifiers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(InvoiceModifierFromJSON)),
    };
}

export function ListInvoiceModifiers200ResponseToJSON(json: any): ListInvoiceModifiers200Response {
    return ListInvoiceModifiers200ResponseToJSONTyped(json, false);
}

export function ListInvoiceModifiers200ResponseToJSONTyped(value?: ListInvoiceModifiers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(InvoiceModifierToJSON)),
    };
}

