/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface ListAccounts200Response
 */
export interface ListAccounts200Response {
    /**
     * 
     * @type {number}
     * @memberof ListAccounts200Response
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListAccounts200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListAccounts200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Account>}
     * @memberof ListAccounts200Response
     */
    results?: Array<Account>;
}

/**
 * Check if a given object implements the ListAccounts200Response interface.
 */
export function instanceOfListAccounts200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListAccounts200ResponseFromJSON(json: any): ListAccounts200Response {
    return ListAccounts200ResponseFromJSONTyped(json, false);
}

export function ListAccounts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAccounts200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(AccountFromJSON)),
    };
}

export function ListAccounts200ResponseToJSON(value?: ListAccounts200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(AccountToJSON)),
    };
}

