/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Note } from './Note';
import {
    NoteFromJSON,
    NoteFromJSONTyped,
    NoteToJSON,
    NoteToJSONTyped,
} from './Note';

/**
 * 
 * @export
 * @interface ListNotes200Response
 */
export interface ListNotes200Response {
    /**
     * 
     * @type {number}
     * @memberof ListNotes200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListNotes200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListNotes200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Note>}
     * @memberof ListNotes200Response
     */
    results: Array<Note>;
}

/**
 * Check if a given object implements the ListNotes200Response interface.
 */
export function instanceOfListNotes200Response(value: object): value is ListNotes200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ListNotes200ResponseFromJSON(json: any): ListNotes200Response {
    return ListNotes200ResponseFromJSONTyped(json, false);
}

export function ListNotes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNotes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(NoteFromJSON)),
    };
}

export function ListNotes200ResponseToJSON(json: any): ListNotes200Response {
    return ListNotes200ResponseToJSONTyped(json, false);
}

export function ListNotes200ResponseToJSONTyped(value?: ListNotes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(NoteToJSON)),
    };
}

