/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Contact } from './Contact';
import {
    ContactFromJSON,
    ContactFromJSONTyped,
    ContactToJSON,
} from './Contact';

/**
 * 
 * @export
 * @interface ListContacts200Response
 */
export interface ListContacts200Response {
    /**
     * 
     * @type {number}
     * @memberof ListContacts200Response
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListContacts200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListContacts200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Contact>}
     * @memberof ListContacts200Response
     */
    results?: Array<Contact>;
}

/**
 * Check if a given object implements the ListContacts200Response interface.
 */
export function instanceOfListContacts200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListContacts200ResponseFromJSON(json: any): ListContacts200Response {
    return ListContacts200ResponseFromJSONTyped(json, false);
}

export function ListContacts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListContacts200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ContactFromJSON)),
    };
}

export function ListContacts200ResponseToJSON(value?: ListContacts200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ContactToJSON)),
    };
}

