/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Task } from './Task';
import {
    TaskFromJSON,
    TaskFromJSONTyped,
    TaskToJSON,
} from './Task';

/**
 * 
 * @export
 * @interface ListTasks200Response
 */
export interface ListTasks200Response {
    /**
     * 
     * @type {number}
     * @memberof ListTasks200Response
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListTasks200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListTasks200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Task>}
     * @memberof ListTasks200Response
     */
    results?: Array<Task>;
}

/**
 * Check if a given object implements the ListTasks200Response interface.
 */
export function instanceOfListTasks200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListTasks200ResponseFromJSON(json: any): ListTasks200Response {
    return ListTasks200ResponseFromJSONTyped(json, false);
}

export function ListTasks200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTasks200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(TaskFromJSON)),
    };
}

export function ListTasks200ResponseToJSON(value?: ListTasks200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(TaskToJSON)),
    };
}

