/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Invoice } from './Invoice';
import {
    InvoiceFromJSON,
    InvoiceFromJSONTyped,
    InvoiceToJSON,
    InvoiceToJSONTyped,
} from './Invoice';

/**
 * 
 * @export
 * @interface ListInvoices200Response
 */
export interface ListInvoices200Response {
    /**
     * 
     * @type {number}
     * @memberof ListInvoices200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListInvoices200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListInvoices200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Invoice>}
     * @memberof ListInvoices200Response
     */
    results: Array<Invoice>;
}

/**
 * Check if a given object implements the ListInvoices200Response interface.
 */
export function instanceOfListInvoices200Response(value: object): value is ListInvoices200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ListInvoices200ResponseFromJSON(json: any): ListInvoices200Response {
    return ListInvoices200ResponseFromJSONTyped(json, false);
}

export function ListInvoices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvoices200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(InvoiceFromJSON)),
    };
}

export function ListInvoices200ResponseToJSON(json: any): ListInvoices200Response {
    return ListInvoices200ResponseToJSONTyped(json, false);
}

export function ListInvoices200ResponseToJSONTyped(value?: ListInvoices200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(InvoiceToJSON)),
    };
}

