/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Company } from './Company';
import {
    CompanyFromJSON,
    CompanyFromJSONTyped,
    CompanyToJSON,
    CompanyToJSONTyped,
} from './Company';

/**
 * 
 * @export
 * @interface ListCompanies200Response
 */
export interface ListCompanies200Response {
    /**
     * 
     * @type {number}
     * @memberof ListCompanies200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListCompanies200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListCompanies200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Company>}
     * @memberof ListCompanies200Response
     */
    results: Array<Company>;
}

/**
 * Check if a given object implements the ListCompanies200Response interface.
 */
export function instanceOfListCompanies200Response(value: object): value is ListCompanies200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ListCompanies200ResponseFromJSON(json: any): ListCompanies200Response {
    return ListCompanies200ResponseFromJSONTyped(json, false);
}

export function ListCompanies200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCompanies200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CompanyFromJSON)),
    };
}

export function ListCompanies200ResponseToJSON(json: any): ListCompanies200Response {
    return ListCompanies200ResponseToJSONTyped(json, false);
}

export function ListCompanies200ResponseToJSONTyped(value?: ListCompanies200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CompanyToJSON)),
    };
}

