/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Invoice } from './Invoice';
import {
    InvoiceFromJSON,
    InvoiceFromJSONTyped,
    InvoiceToJSON,
} from './Invoice';

/**
 * 
 * @export
 * @interface ListInvoices200Response
 */
export interface ListInvoices200Response {
    /**
     * 
     * @type {number}
     * @memberof ListInvoices200Response
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListInvoices200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListInvoices200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Invoice>}
     * @memberof ListInvoices200Response
     */
    results?: Array<Invoice>;
}

/**
 * Check if a given object implements the ListInvoices200Response interface.
 */
export function instanceOfListInvoices200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListInvoices200ResponseFromJSON(json: any): ListInvoices200Response {
    return ListInvoices200ResponseFromJSONTyped(json, false);
}

export function ListInvoices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvoices200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(InvoiceFromJSON)),
    };
}

export function ListInvoices200ResponseToJSON(value?: ListInvoices200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(InvoiceToJSON)),
    };
}

