/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackedTime } from './TrackedTime';
import {
    TrackedTimeFromJSON,
    TrackedTimeFromJSONTyped,
    TrackedTimeToJSON,
    TrackedTimeToJSONTyped,
} from './TrackedTime';

/**
 * 
 * @export
 * @interface ListTrackedTimes200Response
 */
export interface ListTrackedTimes200Response {
    /**
     * 
     * @type {number}
     * @memberof ListTrackedTimes200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListTrackedTimes200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListTrackedTimes200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TrackedTime>}
     * @memberof ListTrackedTimes200Response
     */
    results: Array<TrackedTime>;
}

/**
 * Check if a given object implements the ListTrackedTimes200Response interface.
 */
export function instanceOfListTrackedTimes200Response(value: object): value is ListTrackedTimes200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ListTrackedTimes200ResponseFromJSON(json: any): ListTrackedTimes200Response {
    return ListTrackedTimes200ResponseFromJSONTyped(json, false);
}

export function ListTrackedTimes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTrackedTimes200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TrackedTimeFromJSON)),
    };
}

export function ListTrackedTimes200ResponseToJSON(json: any): ListTrackedTimes200Response {
    return ListTrackedTimes200ResponseToJSONTyped(json, false);
}

export function ListTrackedTimes200ResponseToJSONTyped(value?: ListTrackedTimes200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TrackedTimeToJSON)),
    };
}

