/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TagType } from './TagType';
import {
    TagTypeFromJSON,
    TagTypeFromJSONTyped,
    TagTypeToJSON,
} from './TagType';

/**
 * 
 * @export
 * @interface ListTagTypes200Response
 */
export interface ListTagTypes200Response {
    /**
     * 
     * @type {number}
     * @memberof ListTagTypes200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ListTagTypes200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListTagTypes200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TagType>}
     * @memberof ListTagTypes200Response
     */
    results: Array<TagType>;
}

/**
 * Check if a given object implements the ListTagTypes200Response interface.
 */
export function instanceOfListTagTypes200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "count" in value;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function ListTagTypes200ResponseFromJSON(json: any): ListTagTypes200Response {
    return ListTagTypes200ResponseFromJSONTyped(json, false);
}

export function ListTagTypes200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTagTypes200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TagTypeFromJSON)),
    };
}

export function ListTagTypes200ResponseToJSON(value?: ListTagTypes200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': ((value.results as Array<any>).map(TagTypeToJSON)),
    };
}

