/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OneTimeToken
 */
export interface OneTimeToken {
    /**
     * 
     * @type {string}
     * @memberof OneTimeToken
     */
    key: string;
}

/**
 * Check if a given object implements the OneTimeToken interface.
 */
export function instanceOfOneTimeToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function OneTimeTokenFromJSON(json: any): OneTimeToken {
    return OneTimeTokenFromJSONTyped(json, false);
}

export function OneTimeTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneTimeToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function OneTimeTokenToJSON(value?: OneTimeToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}

