/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OneTimeToken
 */
export interface OneTimeToken {
    /**
     * 
     * @type {string}
     * @memberof OneTimeToken
     */
    key: string;
}

/**
 * Check if a given object implements the OneTimeToken interface.
 */
export function instanceOfOneTimeToken(value: object): value is OneTimeToken {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function OneTimeTokenFromJSON(json: any): OneTimeToken {
    return OneTimeTokenFromJSONTyped(json, false);
}

export function OneTimeTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): OneTimeToken {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function OneTimeTokenToJSON(json: any): OneTimeToken {
    return OneTimeTokenToJSONTyped(json, false);
}

export function OneTimeTokenToJSONTyped(value?: OneTimeToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

