/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectSummaryUnbilledInnerProject } from './ProjectSummaryUnbilledInnerProject';
import {
    ProjectSummaryUnbilledInnerProjectFromJSON,
    ProjectSummaryUnbilledInnerProjectFromJSONTyped,
    ProjectSummaryUnbilledInnerProjectToJSON,
    ProjectSummaryUnbilledInnerProjectToJSONTyped,
} from './ProjectSummaryUnbilledInnerProject';

/**
 * 
 * @export
 * @interface ProjectSummaryInvoicesInner
 */
export interface ProjectSummaryInvoicesInner {
    /**
     * 
     * @type {ProjectSummaryUnbilledInnerProject}
     * @memberof ProjectSummaryInvoicesInner
     */
    project?: ProjectSummaryUnbilledInnerProject;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly totalInvoiced?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly subtotalInvoiced?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly totalPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly totalUnpaid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly invoiceCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly sixMonthSubtotalInvoiced?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly sixMonthTotalInvoiced?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly sixMonthTotalPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly sixMonthTotalUnpaid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoicesInner
     */
    readonly sixMonthInvoiceCount?: number;
}

/**
 * Check if a given object implements the ProjectSummaryInvoicesInner interface.
 */
export function instanceOfProjectSummaryInvoicesInner(value: object): value is ProjectSummaryInvoicesInner {
    return true;
}

export function ProjectSummaryInvoicesInnerFromJSON(json: any): ProjectSummaryInvoicesInner {
    return ProjectSummaryInvoicesInnerFromJSONTyped(json, false);
}

export function ProjectSummaryInvoicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSummaryInvoicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'project': json['project'] == null ? undefined : ProjectSummaryUnbilledInnerProjectFromJSON(json['project']),
        'totalInvoiced': json['total_invoiced'] == null ? undefined : json['total_invoiced'],
        'subtotalInvoiced': json['subtotal_invoiced'] == null ? undefined : json['subtotal_invoiced'],
        'totalPaid': json['total_paid'] == null ? undefined : json['total_paid'],
        'totalUnpaid': json['total_unpaid'] == null ? undefined : json['total_unpaid'],
        'invoiceCount': json['invoice_count'] == null ? undefined : json['invoice_count'],
        'sixMonthSubtotalInvoiced': json['six_month_subtotal_invoiced'] == null ? undefined : json['six_month_subtotal_invoiced'],
        'sixMonthTotalInvoiced': json['six_month_total_invoiced'] == null ? undefined : json['six_month_total_invoiced'],
        'sixMonthTotalPaid': json['six_month_total_paid'] == null ? undefined : json['six_month_total_paid'],
        'sixMonthTotalUnpaid': json['six_month_total_unpaid'] == null ? undefined : json['six_month_total_unpaid'],
        'sixMonthInvoiceCount': json['six_month_invoice_count'] == null ? undefined : json['six_month_invoice_count'],
    };
}

export function ProjectSummaryInvoicesInnerToJSON(json: any): ProjectSummaryInvoicesInner {
    return ProjectSummaryInvoicesInnerToJSONTyped(json, false);
}

export function ProjectSummaryInvoicesInnerToJSONTyped(value?: Omit<ProjectSummaryInvoicesInner, 'total_invoiced'|'subtotal_invoiced'|'total_paid'|'total_unpaid'|'invoice_count'|'six_month_subtotal_invoiced'|'six_month_total_invoiced'|'six_month_total_paid'|'six_month_total_unpaid'|'six_month_invoice_count'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': ProjectSummaryUnbilledInnerProjectToJSON(value['project']),
    };
}

