/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectSummaryInvoices } from './ProjectSummaryInvoices';
import {
    ProjectSummaryInvoicesFromJSON,
    ProjectSummaryInvoicesFromJSONTyped,
    ProjectSummaryInvoicesToJSON,
    ProjectSummaryInvoicesToJSONTyped,
} from './ProjectSummaryInvoices';
import type { ProjectSummaryUnbilledInner } from './ProjectSummaryUnbilledInner';
import {
    ProjectSummaryUnbilledInnerFromJSON,
    ProjectSummaryUnbilledInnerFromJSONTyped,
    ProjectSummaryUnbilledInnerToJSON,
    ProjectSummaryUnbilledInnerToJSONTyped,
} from './ProjectSummaryUnbilledInner';

/**
 * 
 * @export
 * @interface ProjectSummary
 */
export interface ProjectSummary {
    /**
     * 
     * @type {Array<ProjectSummaryUnbilledInner>}
     * @memberof ProjectSummary
     */
    unbilled: Array<ProjectSummaryUnbilledInner>;
    /**
     * 
     * @type {ProjectSummaryInvoices}
     * @memberof ProjectSummary
     */
    invoices: ProjectSummaryInvoices;
}

/**
 * Check if a given object implements the ProjectSummary interface.
 */
export function instanceOfProjectSummary(value: object): value is ProjectSummary {
    if (!('unbilled' in value) || value['unbilled'] === undefined) return false;
    if (!('invoices' in value) || value['invoices'] === undefined) return false;
    return true;
}

export function ProjectSummaryFromJSON(json: any): ProjectSummary {
    return ProjectSummaryFromJSONTyped(json, false);
}

export function ProjectSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'unbilled': ((json['unbilled'] as Array<any>).map(ProjectSummaryUnbilledInnerFromJSON)),
        'invoices': ProjectSummaryInvoicesFromJSON(json['invoices']),
    };
}

export function ProjectSummaryToJSON(json: any): ProjectSummary {
    return ProjectSummaryToJSONTyped(json, false);
}

export function ProjectSummaryToJSONTyped(value?: ProjectSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unbilled': ((value['unbilled'] as Array<any>).map(ProjectSummaryUnbilledInnerToJSON)),
        'invoices': ProjectSummaryInvoicesToJSON(value['invoices']),
    };
}

