/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectSummaryInvoices
 */
export interface ProjectSummaryInvoices {
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoices
     */
    readonly subtotalInvoiced?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoices
     */
    readonly totalInvoiced?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoices
     */
    readonly totalPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoices
     */
    readonly totalUnpaid?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryInvoices
     */
    readonly invoiceCount?: number;
}

/**
 * Check if a given object implements the ProjectSummaryInvoices interface.
 */
export function instanceOfProjectSummaryInvoices(value: object): value is ProjectSummaryInvoices {
    return true;
}

export function ProjectSummaryInvoicesFromJSON(json: any): ProjectSummaryInvoices {
    return ProjectSummaryInvoicesFromJSONTyped(json, false);
}

export function ProjectSummaryInvoicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSummaryInvoices {
    if (json == null) {
        return json;
    }
    return {
        
        'subtotalInvoiced': json['subtotal_invoiced'] == null ? undefined : json['subtotal_invoiced'],
        'totalInvoiced': json['total_invoiced'] == null ? undefined : json['total_invoiced'],
        'totalPaid': json['total_paid'] == null ? undefined : json['total_paid'],
        'totalUnpaid': json['total_unpaid'] == null ? undefined : json['total_unpaid'],
        'invoiceCount': json['invoice_count'] == null ? undefined : json['invoice_count'],
    };
}

export function ProjectSummaryInvoicesToJSON(json: any): ProjectSummaryInvoices {
    return ProjectSummaryInvoicesToJSONTyped(json, false);
}

export function ProjectSummaryInvoicesToJSONTyped(value?: Omit<ProjectSummaryInvoices, 'subtotal_invoiced'|'total_invoiced'|'total_paid'|'total_unpaid'|'invoice_count'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
    };
}

