/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    contact: number;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly uninvoicedHours?: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    readonly totalPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    hourlyRate?: number;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    weeklyRate?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    archived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    defaultTask?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    readonly nextSequenceNum?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    billingUnit?: ProjectBillingUnitEnum | null;
}


/**
 * @export
 */
export const ProjectBillingUnitEnum = {
    Hour: 'HOUR',
    Day: 'DAY',
    Week: 'WEEK'
} as const;
export type ProjectBillingUnitEnum = typeof ProjectBillingUnitEnum[keyof typeof ProjectBillingUnitEnum];


/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): value is Project {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('contact' in value) || value['contact'] === undefined) return false;
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'contact': json['contact'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'uninvoicedHours': json['uninvoiced_hours'] == null ? undefined : json['uninvoiced_hours'],
        'totalPaid': json['total_paid'] == null ? undefined : json['total_paid'],
        'hourlyRate': json['hourly_rate'] == null ? undefined : json['hourly_rate'],
        'weeklyRate': json['weekly_rate'] == null ? undefined : json['weekly_rate'],
        'archived': json['archived'] == null ? undefined : json['archived'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'defaultTask': json['default_task'] == null ? undefined : json['default_task'],
        'nextSequenceNum': json['next_sequence_num'] == null ? undefined : json['next_sequence_num'],
        'billingUnit': json['billing_unit'] == null ? undefined : json['billing_unit'],
    };
}

export function ProjectToJSON(json: any): Project {
    return ProjectToJSONTyped(json, false);
}

export function ProjectToJSONTyped(value?: Omit<Project, 'id'|'created_at'|'uninvoiced_hours'|'total_paid'|'next_sequence_num'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'contact': value['contact'],
        'hourly_rate': value['hourlyRate'],
        'weekly_rate': value['weeklyRate'],
        'archived': value['archived'],
        'currency': value['currency'],
        'default_task': value['defaultTask'],
        'billing_unit': value['billingUnit'],
    };
}

