/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectSummaryUnbilledInnerPreviousInvoice
 */
export interface ProjectSummaryUnbilledInnerPreviousInvoice {
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    sequenceNum?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    project: number;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    readonly issuedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    paidAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    totalPaid?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    totalDue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    subtotalDue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    status?: ProjectSummaryUnbilledInnerPreviousInvoiceStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    reference?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    groupBy?: ProjectSummaryUnbilledInnerPreviousInvoiceGroupByEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    showHours?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    timeslips: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    tasks: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    modifier?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    readonly pdfName?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    readonly name?: string;
    /**
     * 
     * @type {number}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    exchangeRate?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectSummaryUnbilledInnerPreviousInvoice
     */
    billingUnit?: ProjectSummaryUnbilledInnerPreviousInvoiceBillingUnitEnum | null;
}


/**
 * @export
 */
export const ProjectSummaryUnbilledInnerPreviousInvoiceStatusEnum = {
    Draft: 'DRAFT',
    Issued: 'ISSUED',
    Paid: 'PAID'
} as const;
export type ProjectSummaryUnbilledInnerPreviousInvoiceStatusEnum = typeof ProjectSummaryUnbilledInnerPreviousInvoiceStatusEnum[keyof typeof ProjectSummaryUnbilledInnerPreviousInvoiceStatusEnum];

/**
 * @export
 */
export const ProjectSummaryUnbilledInnerPreviousInvoiceGroupByEnum = {
    Tasks: 'tasks',
    Timeslips: 'timeslips'
} as const;
export type ProjectSummaryUnbilledInnerPreviousInvoiceGroupByEnum = typeof ProjectSummaryUnbilledInnerPreviousInvoiceGroupByEnum[keyof typeof ProjectSummaryUnbilledInnerPreviousInvoiceGroupByEnum];

/**
 * @export
 */
export const ProjectSummaryUnbilledInnerPreviousInvoiceBillingUnitEnum = {
    Hour: 'HOUR',
    Day: 'DAY',
    Week: 'WEEK'
} as const;
export type ProjectSummaryUnbilledInnerPreviousInvoiceBillingUnitEnum = typeof ProjectSummaryUnbilledInnerPreviousInvoiceBillingUnitEnum[keyof typeof ProjectSummaryUnbilledInnerPreviousInvoiceBillingUnitEnum];


/**
 * Check if a given object implements the ProjectSummaryUnbilledInnerPreviousInvoice interface.
 */
export function instanceOfProjectSummaryUnbilledInnerPreviousInvoice(value: object): value is ProjectSummaryUnbilledInnerPreviousInvoice {
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('timeslips' in value) || value['timeslips'] === undefined) return false;
    if (!('tasks' in value) || value['tasks'] === undefined) return false;
    return true;
}

export function ProjectSummaryUnbilledInnerPreviousInvoiceFromJSON(json: any): ProjectSummaryUnbilledInnerPreviousInvoice {
    return ProjectSummaryUnbilledInnerPreviousInvoiceFromJSONTyped(json, false);
}

export function ProjectSummaryUnbilledInnerPreviousInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSummaryUnbilledInnerPreviousInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sequenceNum': json['sequence_num'] == null ? undefined : json['sequence_num'],
        'project': json['project'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'issuedAt': json['issued_at'] == null ? undefined : (new Date(json['issued_at'])),
        'paidAt': json['paid_at'] == null ? undefined : (new Date(json['paid_at'])),
        'dueDate': json['due_date'] == null ? undefined : (new Date(json['due_date'])),
        'totalPaid': json['total_paid'] == null ? undefined : json['total_paid'],
        'totalDue': json['total_due'] == null ? undefined : json['total_due'],
        'subtotalDue': json['subtotal_due'] == null ? undefined : json['subtotal_due'],
        'status': json['status'] == null ? undefined : json['status'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'groupBy': json['group_by'] == null ? undefined : json['group_by'],
        'showHours': json['show_hours'] == null ? undefined : json['show_hours'],
        'timeslips': json['timeslips'],
        'tasks': json['tasks'],
        'modifier': json['modifier'] == null ? undefined : json['modifier'],
        'pdfName': json['pdf_name'] == null ? undefined : json['pdf_name'],
        'name': json['name'] == null ? undefined : json['name'],
        'exchangeRate': json['exchange_rate'] == null ? undefined : json['exchange_rate'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'billingUnit': json['billing_unit'] == null ? undefined : json['billing_unit'],
    };
}

export function ProjectSummaryUnbilledInnerPreviousInvoiceToJSON(json: any): ProjectSummaryUnbilledInnerPreviousInvoice {
    return ProjectSummaryUnbilledInnerPreviousInvoiceToJSONTyped(json, false);
}

export function ProjectSummaryUnbilledInnerPreviousInvoiceToJSONTyped(value?: Omit<ProjectSummaryUnbilledInnerPreviousInvoice, 'id'|'created_at'|'issued_at'|'pdf_name'|'name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sequence_num': value['sequenceNum'],
        'project': value['project'],
        'paid_at': value['paidAt'] == null ? value['paidAt'] : value['paidAt'].toISOString(),
        'due_date': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString().substring(0,10),
        'total_paid': value['totalPaid'],
        'total_due': value['totalDue'],
        'subtotal_due': value['subtotalDue'],
        'status': value['status'],
        'reference': value['reference'],
        'group_by': value['groupBy'],
        'show_hours': value['showHours'],
        'timeslips': value['timeslips'],
        'tasks': value['tasks'],
        'modifier': value['modifier'],
        'exchange_rate': value['exchangeRate'],
        'currency': value['currency'],
        'billing_unit': value['billingUnit'],
    };
}

