/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SSO
 */
export interface SSO {
    /**
     * 
     * @type {string}
     * @memberof SSO
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof SSO
     */
    readonly token?: string;
}

/**
 * Check if a given object implements the SSO interface.
 */
export function instanceOfSSO(value: object): value is SSO {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function SSOFromJSON(json: any): SSO {
    return SSOFromJSONTyped(json, false);
}

export function SSOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SSO {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function SSOToJSON(json: any): SSO {
    return SSOToJSONTyped(json, false);
}

export function SSOToJSONTyped(value?: Omit<SSO, 'token'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

