/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagType
 */
export interface TagType {
    /**
     * 
     * @type {string}
     * @memberof TagType
     */
    tagType: string;
    /**
     * 
     * @type {string}
     * @memberof TagType
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof TagType
     */
    displayValue: string;
    /**
     * 
     * @type {number}
     * @memberof TagType
     */
    count: number;
}

/**
 * Check if a given object implements the TagType interface.
 */
export function instanceOfTagType(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tagType" in value;
    isInstance = isInstance && "value" in value;
    isInstance = isInstance && "displayValue" in value;
    isInstance = isInstance && "count" in value;

    return isInstance;
}

export function TagTypeFromJSON(json: any): TagType {
    return TagTypeFromJSONTyped(json, false);
}

export function TagTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tagType': json['tag_type'],
        'value': json['value'],
        'displayValue': json['display_value'],
        'count': json['count'],
    };
}

export function TagTypeToJSON(value?: TagType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tag_type': value.tagType,
        'value': value.value,
        'display_value': value.displayValue,
        'count': value.count,
    };
}

