/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TaskSummaryInvoices,
    TaskSummaryInvoicesFromJSON,
    TaskSummaryInvoicesFromJSONTyped,
    TaskSummaryInvoicesToJSON,
    TaskSummaryTimeslips,
    TaskSummaryTimeslipsFromJSON,
    TaskSummaryTimeslipsFromJSONTyped,
    TaskSummaryTimeslipsToJSON,
} from './';

/**
 * 
 * @export
 * @interface TaskSummary
 */
export interface TaskSummary {
    /**
     * 
     * @type {Array<TaskSummaryInvoices>}
     * @memberof TaskSummary
     */
    invoices: Array<TaskSummaryInvoices>;
    /**
     * 
     * @type {Array<TaskSummaryTimeslips>}
     * @memberof TaskSummary
     */
    timeslips: Array<TaskSummaryTimeslips>;
}

export function TaskSummaryFromJSON(json: any): TaskSummary {
    return TaskSummaryFromJSONTyped(json, false);
}

export function TaskSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'invoices': ((json['invoices'] as Array<any>).map(TaskSummaryInvoicesFromJSON)),
        'timeslips': ((json['timeslips'] as Array<any>).map(TaskSummaryTimeslipsFromJSON)),
    };
}

export function TaskSummaryToJSON(value?: TaskSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'invoices': ((value.invoices as Array<any>).map(TaskSummaryInvoicesToJSON)),
        'timeslips': ((value.timeslips as Array<any>).map(TaskSummaryTimeslipsToJSON)),
    };
}


