/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaskSummaryInvoicesInner } from './TaskSummaryInvoicesInner';
import {
    TaskSummaryInvoicesInnerFromJSON,
    TaskSummaryInvoicesInnerFromJSONTyped,
    TaskSummaryInvoicesInnerToJSON,
    TaskSummaryInvoicesInnerToJSONTyped,
} from './TaskSummaryInvoicesInner';
import type { TaskSummaryTimeslipsInner } from './TaskSummaryTimeslipsInner';
import {
    TaskSummaryTimeslipsInnerFromJSON,
    TaskSummaryTimeslipsInnerFromJSONTyped,
    TaskSummaryTimeslipsInnerToJSON,
    TaskSummaryTimeslipsInnerToJSONTyped,
} from './TaskSummaryTimeslipsInner';

/**
 * 
 * @export
 * @interface TaskSummary
 */
export interface TaskSummary {
    /**
     * 
     * @type {Array<TaskSummaryInvoicesInner>}
     * @memberof TaskSummary
     */
    invoices: Array<TaskSummaryInvoicesInner>;
    /**
     * 
     * @type {Array<TaskSummaryTimeslipsInner>}
     * @memberof TaskSummary
     */
    timeslips: Array<TaskSummaryTimeslipsInner>;
}

/**
 * Check if a given object implements the TaskSummary interface.
 */
export function instanceOfTaskSummary(value: object): value is TaskSummary {
    if (!('invoices' in value) || value['invoices'] === undefined) return false;
    if (!('timeslips' in value) || value['timeslips'] === undefined) return false;
    return true;
}

export function TaskSummaryFromJSON(json: any): TaskSummary {
    return TaskSummaryFromJSONTyped(json, false);
}

export function TaskSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'invoices': ((json['invoices'] as Array<any>).map(TaskSummaryInvoicesInnerFromJSON)),
        'timeslips': ((json['timeslips'] as Array<any>).map(TaskSummaryTimeslipsInnerFromJSON)),
    };
}

export function TaskSummaryToJSON(json: any): TaskSummary {
    return TaskSummaryToJSONTyped(json, false);
}

export function TaskSummaryToJSONTyped(value?: TaskSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoices': ((value['invoices'] as Array<any>).map(TaskSummaryInvoicesInnerToJSON)),
        'timeslips': ((value['timeslips'] as Array<any>).map(TaskSummaryTimeslipsInnerToJSON)),
    };
}

