/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskSummaryTimeslipsInner
 */
export interface TaskSummaryTimeslipsInner {
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    user: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    hours?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    hourlyRate?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    task: number | null;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    invoice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslipsInner
     */
    readonly cost?: number;
    /**
     * 
     * @type {Date}
     * @memberof TaskSummaryTimeslipsInner
     */
    date: Date;
}

/**
 * Check if a given object implements the TaskSummaryTimeslipsInner interface.
 */
export function instanceOfTaskSummaryTimeslipsInner(value: object): value is TaskSummaryTimeslipsInner {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('task' in value) || value['task'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function TaskSummaryTimeslipsInnerFromJSON(json: any): TaskSummaryTimeslipsInner {
    return TaskSummaryTimeslipsInnerFromJSONTyped(json, false);
}

export function TaskSummaryTimeslipsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskSummaryTimeslipsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'user': json['user'],
        'hours': json['hours'] == null ? undefined : json['hours'],
        'hourlyRate': json['hourly_rate'] == null ? undefined : json['hourly_rate'],
        'project': json['project'],
        'task': json['task'],
        'invoice': json['invoice'] == null ? undefined : json['invoice'],
        'cost': json['cost'] == null ? undefined : json['cost'],
        'date': (new Date(json['date'])),
    };
}

export function TaskSummaryTimeslipsInnerToJSON(json: any): TaskSummaryTimeslipsInner {
    return TaskSummaryTimeslipsInnerToJSONTyped(json, false);
}

export function TaskSummaryTimeslipsInnerToJSONTyped(value?: Omit<TaskSummaryTimeslipsInner, 'id'|'cost'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': value['user'],
        'hours': value['hours'],
        'hourly_rate': value['hourlyRate'],
        'project': value['project'],
        'task': value['task'],
        'invoice': value['invoice'],
        'date': value['date'].toISOString().substring(0,10),
    };
}

