/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskNotesInner
 */
export interface TaskNotesInner {
    /**
     * 
     * @type {string}
     * @memberof TaskNotesInner
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TaskNotesInner
     */
    contentType?: TaskNotesInnerContentTypeEnum;
}


/**
 * @export
 */
export const TaskNotesInnerContentTypeEnum = {
    Text: 'TEXT'
} as const;
export type TaskNotesInnerContentTypeEnum = typeof TaskNotesInnerContentTypeEnum[keyof typeof TaskNotesInnerContentTypeEnum];


/**
 * Check if a given object implements the TaskNotesInner interface.
 */
export function instanceOfTaskNotesInner(value: object): value is TaskNotesInner {
    return true;
}

export function TaskNotesInnerFromJSON(json: any): TaskNotesInner {
    return TaskNotesInnerFromJSONTyped(json, false);
}

export function TaskNotesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskNotesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
    };
}

export function TaskNotesInnerToJSON(json: any): TaskNotesInner {
    return TaskNotesInnerToJSONTyped(json, false);
}

export function TaskNotesInnerToJSONTyped(value?: TaskNotesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'content_type': value['contentType'],
    };
}

