/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaskSummaryTimeslips
 */
export interface TaskSummaryTimeslips {
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    user: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    hours?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    hourlyRate?: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    task: number | null;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    invoice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TaskSummaryTimeslips
     */
    readonly cost?: number;
    /**
     * 
     * @type {Date}
     * @memberof TaskSummaryTimeslips
     */
    date: Date;
}

export function TaskSummaryTimeslipsFromJSON(json: any): TaskSummaryTimeslips {
    return TaskSummaryTimeslipsFromJSONTyped(json, false);
}

export function TaskSummaryTimeslipsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskSummaryTimeslips {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'user': json['user'],
        'hours': !exists(json, 'hours') ? undefined : json['hours'],
        'hourlyRate': !exists(json, 'hourly_rate') ? undefined : json['hourly_rate'],
        'project': json['project'],
        'task': json['task'],
        'invoice': !exists(json, 'invoice') ? undefined : json['invoice'],
        'cost': !exists(json, 'cost') ? undefined : json['cost'],
        'date': (new Date(json['date'])),
    };
}

export function TaskSummaryTimeslipsToJSON(value?: TaskSummaryTimeslips | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': value.user,
        'hours': value.hours,
        'hourly_rate': value.hourlyRate,
        'project': value.project,
        'task': value.task,
        'invoice': value.invoice,
        'date': (value.date.toISOString().substr(0,10)),
    };
}


