/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackedTime
 */
export interface TrackedTime {
    /**
     * 
     * @type {number}
     * @memberof TrackedTime
     */
    readonly id?: number;
    /**
     * 
     * @type {number}
     * @memberof TrackedTime
     */
    project: number;
    /**
     * 
     * @type {number}
     * @memberof TrackedTime
     */
    task?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TrackedTime
     */
    timeSlip?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TrackedTime
     */
    startedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof TrackedTime
     */
    endedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TrackedTime
     */
    comment?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TrackedTime
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof TrackedTime
     */
    readonly duration?: string;
}

/**
 * Check if a given object implements the TrackedTime interface.
 */
export function instanceOfTrackedTime(value: object): value is TrackedTime {
    if (!('project' in value) || value['project'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    return true;
}

export function TrackedTimeFromJSON(json: any): TrackedTime {
    return TrackedTimeFromJSONTyped(json, false);
}

export function TrackedTimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackedTime {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'project': json['project'],
        'task': json['task'] == null ? undefined : json['task'],
        'timeSlip': json['time_slip'] == null ? undefined : json['time_slip'],
        'startedAt': (new Date(json['started_at'])),
        'endedAt': json['ended_at'] == null ? undefined : (new Date(json['ended_at'])),
        'comment': json['comment'] == null ? undefined : json['comment'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'duration': json['duration'] == null ? undefined : json['duration'],
    };
}

export function TrackedTimeToJSON(json: any): TrackedTime {
    return TrackedTimeToJSONTyped(json, false);
}

export function TrackedTimeToJSONTyped(value?: Omit<TrackedTime, 'id'|'created_at'|'duration'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'project': value['project'],
        'task': value['task'],
        'time_slip': value['timeSlip'],
        'started_at': value['startedAt'].toISOString(),
        'ended_at': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
        'comment': value['comment'],
    };
}

