"""
Django settings for soitgoes project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys
import logging

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = "DEV" in os.environ
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

ALLOWED_HOSTS = [
    "tracking.local",
    "tracking.stuartquin.com",
    "tracking.cloud.stuartquin.com",
    "tracking-dev.cloud.stuartquin.com",
    "localhost",
]


# Application definition

INSTALLED_APPS = [
    "journal",
    "users",
    "crm",
    "corsheaders",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    # CorsMiddleware must run before any middleware that generates
    # responses (CommonMiddleware, etc.) so CORS headers are applied to all
    # responses, including preflight OPTIONS for the Firefox extension.
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# django-cors-headers 4.x renamed CORS_ORIGIN_ALLOW_ALL to
# CORS_ALLOW_ALL_ORIGINS (the old name is kept for backwards compat but
# set the new one to be explicit). The Firefox extension talks to the API
# from a moz-extension:// origin and needs CORS headers on responses.
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = "soitgoes.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}


WSGI_APPLICATION = "soitgoes.wsgi.application"


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DATABASE_NAME", os.path.join(BASE_DIR, "db.sqlite3")),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "COERCE_DECIMAL_TO_STRING": False,
    "PAGE_SIZE": 250,
}


# --- Security / cookie hardening -----------------------------------------
# Dev stays permissive; production (no DEV env var) enforces HTTPS-only
# cookies and trusts the X-Forwarded-Proto header so request.is_secure()
# returns True behind a TLS-terminating proxy.
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    # HTTPS redirection is handled by the reverse proxy / load balancer that
    # terminates TLS. Doing it here too would (a) break the Django test client,
    # which makes plain-HTTP requests that SecurityMiddleware would 301 to a
    # text/html HTTPS page, and (b) risk a redirect loop if the proxy also
    # redirects. Keep app-level redirect off and let the proxy own it.
    # SECURE_SSL_REDIRECT = True

# Session cookies should be inaccessible to JavaScript (Django's default is
# True). The previous SESSION_COOKIE_HTTPONLY = False exposed the session id
# to XSS, so restore the default by simply not overriding it.

# CSRF_COOKIE_SAMESITE and SESSION_COOKIE_SAMESITE default to "Lax", which is
# correct: it blocks cookies on cross-site POSTs without breaking top-level
# navigation. Don't set them to "None" unless you have a genuine cross-site
# session-authenticated SPA.

CSRF_TRUSTED_ORIGINS = [
    "http://localhost",
    "http://localhost:8080",
    "http://localhost:8000",
    "https://tracking.cloud.stuartquin.com",
    "https://tracking-dev.cloud.stuartquin.com",
]

OPEN_EXCHANGE_RATES_APP_ID = os.environ.get("OPEN_EXCHANGE_RATES_APP_ID")

OSSSO_API_URL = os.environ.get("OSSSO_API_URL")
OSSSO_API_TOKEN = os.environ.get("OSSSO_API_TOKEN")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

