# Generated by Django 5.1.1 on 2025-02-22 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0057_alter_account_id_alter_activity_id_alter_billing_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('opening_balance', models.IntegerField(help_text='Initial value to offset total generated from transactions')),
                ('name', models.TextField()),
                ('bank_name', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='journal.account')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.TextField(db_index=True)),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_type', models.TextField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='financeapp.bankaccount')),
            ],
        ),
    ]
