# Generated by Django 5.1.1 on 2025-02-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_alter_bankaccount_uuid'),
        ('journal', '0057_alter_account_id_alter_activity_id_alter_billing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conditions', models.JSONField()),
                ('tag_definitions', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_rules', to='journal.account')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='financeapp.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag_type', models.TextField(db_index=True)),
                ('value', models.TextField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='financeapp.banktransaction')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='financeapp.rule')),
            ],
        ),
    ]
