name: Test and Release

on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
    branches: master

jobs:
  test-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./api
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        env:
          DJANGO_SECRET_KEY: abc-456
        working-directory: ./api
        run: |
          python manage.py test

  test-ui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        working-directory: ./ui
        run: npm ci
      - name: Build
        working-directory: ./ui
        run: npm run build --if-present
      - name: Test
        working-directory: ./ui
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [test-api, test-ui]
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST_KEY }}
      - name: Push to Dokku Dev
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          ssh dokku@cloud.stuartquin.com -t "dokku config:set --no-restart tracking-dev GIT_BRANCH=${GITHUB_REF}"
          git remote add dokku dokku@cloud.stuartquin.com:tracking-dev
          git push -f dokku ${GITHUB_SHA}:master
      - name: Push to Dokku Prod
        if: startsWith( github.ref, 'refs/tags/v')
        run: |
          ssh dokku@cloud.stuartquin.com -t "dokku config:set --no-restart tracking GIT_BRANCH=${GITHUB_REF}"
          git remote add dokku dokku@cloud.stuartquin.com:tracking
          git push -f dokku ${GITHUB_SHA}:master

  deploy-ui:
    runs-on: ubuntu-latest
    needs: [test-api, test-ui]
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        working-directory: ./ui
        run: npm ci

      - name: Build
        working-directory: ./ui
        run: npm run build --if-present

      - name: Deploy UI Dev via SCP-action
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: appleboy/scp-action@98930d398ce425af0148ea8a0e3295cd04fe2b7a
        with:
          host: cloud.stuartquin.com
          username: dokku
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          strip_components: 2
          source: "ui/dist/*"
          target: /home/dokku/storage/tracking-dev/build
